name 'travis-cookbook-test'
maintainer 'Joshua Miller'
maintainer_email 'cookbooks@fitsnips.net'
license 'all_rights'
description 'Installs/Configures travis-cookbook-test'
long_description 'Installs/Configures travis-cookbook-test'
version '0.1.0'
